response-property-description-changed
request-property-description-changed
api-operation-summary-changed
api-operation-description-changed
Example changes (safe to ignore)
response-property-example-changed
request-property-example-changed
api-operation-example-changed