# oasdiff Error Ignore Configuration
# This file defines which breaking change errors should be ignored
# Use this to temporarily suppress known breaking changes during development

# === Temporary Suppressions ===
# Uncomment rules below to ignore specific breaking changes

# API path removals (use carefully - these are usually real breaking changes)
# - api-path-removed-without-deprecation
# - api-removed-without-deprecation

# Request property changes (use for backwards compatibility periods)
# - request-property-became-required  # Ignore making optional fields required
# - request-property-removed           # Ignore removing request properties
# - request-property-type-changed      # Ignore changing request property types

# Response property changes (generally safe to ignore additions)
# - response-property-removed          # Ignore removing response properties
# - response-property-type-changed     # Ignore changing response property types

# Parameter changes
# - request-parameter-became-required  # Ignore making optional parameters required
# - request-parameter-removed          # Ignore removing parameters
# - request-parameter-type-changed     # Ignore changing parameter types

# Security changes (use with extreme caution)
# - api-security-removed               # Ignore security requirement removals
# - api-global-security-removed        # Ignore global security removals

# === Development Environment Suppressions ===
# Rules to ignore in development/testing environments only

# Documentation changes (safe to ignore)
- response-property-description-changed
- request-property-description-changed
- api-operation-summary-changed
- api-operation-description-changed

# Example changes (safe to ignore)
- response-property-example-changed
- request-property-example-changed
- api-operation-example-changed

# === Hyperswitch-Specific Ignores ===
# Project-specific rules that may be safely ignored

# Internal field changes (if you have internal-only fields)
# - request-property-removed:/^x-internal-/
# - response-property-removed:/^x-internal-/

# Experimental feature changes (use during feature development)
# - request-property-removed:/experimental/
# - response-property-removed:/experimental/

# Beta endpoint changes (if you have beta APIs)
# - api-path-removed-without-deprecation:/beta/
# - api-removed-without-deprecation:/beta/

# === Path-Based Ignores ===
# Ignore changes to specific paths or patterns

# Ignore changes to health check endpoints
# - api-path-removed-without-deprecation:/health
# - api-removed-without-deprecation:/health

# Ignore changes to internal admin endpoints  
# - api-path-removed-without-deprecation:/admin/
# - api-removed-without-deprecation:/admin/

# Ignore changes to development/testing endpoints
# - api-path-removed-without-deprecation:/dev/
# - api-path-removed-without-deprecation:/test/

# === Conditional Ignores ===
# Rules to ignore only under specific conditions

# Ignore property removals for deprecated API versions
# - response-property-removed:/.*/v1/.*/ # Ignore for v1 API only
# - request-property-removed:/.*/v1/.*/  # Ignore for v1 API only

# === Time-Based Ignores ===
# These can be uncommented temporarily and should be removed after fixes

# Ignore during migration periods (remove after migration complete)
# migration-start-date: "2024-01-01"
# migration-end-date: "2024-06-01"
# temporary-ignores:
#   - request-property-became-required
#   - response-property-removed

# === Comments and Notes ===
# Use this section to document why certain rules are ignored
# 
# Example:
# - request-property-became-required:customer_id
#   # Temporarily ignored while we update client libraries
#   # Remove by: 2024-12-31
#   # Tracking issue: HYPER-1234